Add initial schema and automatic interface generation
harp-tech/device.outputexpander pull request #1
Opened 2023-04-25 13:57 UTC by bruno-f-cruz

This PR:
 - Refactors the current repository directory structure in accordance with the latest agreed upon harptech specs;
 - Adds a first schema version for the Harp Output Expander device (device.yml) and the necessary .Net generators to build the high-level bonsai interface.

2023-05-15 22:11 UTC, filcarv commented
**Hardware/Mechanical**'s **README** file should be updated to Copyright Filipe Carvalho 2020 **-2023**

The Firmware solution name should be renamed to **OutputExpander** in order to maintain coherence with the other repos.

The InputExpander project of Atmel Studio is still available in Solution Explorer. Should be removed.

2023-05-16 09:30 UTC, bruno-f-cruz commented
> Hardware/Mechanical's README file should be updated to Copyright Filipe Carvalho 2020 -2023
Done

> The Firmware solution name should be renamed to OutputExpander in order to maintain coherence with the other repos.
> The InputExpander project of Atmel Studio is still available in Solution Explorer. Should be removed.
As I am not super comfortable editing these solutions files, can you change them and PR into my branch? thanks!

2023-06-01 15:27 UTC, glopesdev requested changes

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +  Pwm:
Consider renaming to `PwmChannels`

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +  Stim:
Consider renaming to `StimChannels`

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +  EnableFlag:
This can be removed as it is built into the Harp package

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +  ExpansionBoardTypes:
Rename to `ExpansionBoardType`

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +      At00Hz: 1
Rename to `SamplingRate100Hz` (or consistent with above)

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +      At50Hz: 0
Consider alternatives to `At`:
  - [x] `SamplingRate50Hz`
  - [ ] `Sampling50Hz`
  - [ ] `Fs50Hz` / `FS50Hz`

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +    access: Write
Add missing `Event` access

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +  PwmRiseEventEnable:
Consider renaming to `PwmRiseEvent`

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +    maskType: ExpansionBoardTypes
Rename to `ExpansionBoardType`

2023-06-01 15:27 UTC, glopesdev commented on device.yml
> +    maskType: EncoderSamplingRate
Consider renaming the mask type to `EncoderSamplingRateMode`

2023-06-07 17:20 UTC, glopesdev approved these changes

2023-06-07 17:20 UTC, merged